# 业务代码错误信息配置 
# docs: https://github.com/nodeca/js-yaml

# 10000 - 99999 admin-api-error
10000: 参数校验异常
10001: 系统用户已存在
10002: 填写验证码有误
10003: 用户名密码有误
10004: 节点路由已存在
10005: 权限必须包含父节点
10006: 非法操作：该节点仅支持目录类型父节点
10007: 非法操作：节点类型无法直接转换
10008: 该角色存在关联用户，请先删除关联用户
10009: 该部门存在关联用户，请先删除关联用户

# token相关
11001: 登录无效或无权限访问
11002: 登录身份已过期

# OSS相关
20001: 文件上传失败